#!/usr/bin/env bash
# Create custom 404 page.

apt-get -y update
apt-get -y install nginx

cd /var/www/html || exit

PATH="/var/www/html/custom_404.html"

echo "Holberton School" > "index.html"
echo "Ceci n'est pas une page" > "custom_404.html"

STRING="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "24i $STRING" /etc/nginx/sites-available/default

ERROR="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot $PATH;\n\t\tinternal;\n\t}"
sed -i "28i $ERROR" /etc/nginx/sites-available/default

service nginx restart
