#!/usr/bin/env bash
# Create custom 404 page.

ERROR="Ceci n'est pas une page"
REDIR="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
NFOUND="\\\terror_page 404 /custom_404.html;\n\
        location = /custom_404.html {\n\
                root /var/www/html;\n\
                internal;\
        }"


apt update -y
apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

sed -i "24i $REDIR" /etc/nginx/sites-available/default
sed -i "26i $NFOUND" /etc/nginx/sites-available/default
echo "$ERROR" > /var/www/html/custom_404.html

service nginx restart
