#!/usr/bin/env bash
# Install and Configures HAproxy

sudo apt-get -y update
sudo apt-get install haproxy

sudo echo "\nfrontend firstbalance\n
       \tbind *:80\n
       \tmode http\n
       \toption forwardfor\n
       \tdefault_backend webservers\n\n
backend webservers\n\
       \tbalance roundrobin\n
       \tserver 1531-web-01 35.229.108.128:80\n
       \tserver 1531-web-02 107.21.161.159:80\n" >> /etc/haproxy/haproxy.cfg


sudo service haproxy start
