#!/usr/bin/env bash
# Debugs listening port

sed -i "s/ipv6only=on//g" /etc/nginx/sites-available/default
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
