#!/usr/bin/env bash
# Debugs listening port

sudo service nginx stop
kill -9 "$(psgrep nginx)"
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx start
