#!/usr/bin/env bash
# asjdlashdkjaskldmñasldasd

kill -9 "$(pgrep apache2)"
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start